### ISSUE TITLE
Need a more detailed README.md file

### ISSUE THREAD

**Issue by trystant** [chevinbrown/tracker#1]
As of now, I have no idea what this project is about beyond the name "tracker".  A [README.md template](https://gist.github.com/jxson/1784669) filled out for this project would help potential job evaluators have a better idea of what the project is about and what it does.

**Comment by chevinbrown** [comment]
@trystant, added a readme. Does that help?

**Comment by trystant** [comment]
It does, but it doesn't have all the information listed in the template above. Did you click on that link?

**Comment by chevinbrown** [comment]
@trystant, do you approve of the update? I'll close if it makes sense now.
